### PR TITLE
A convenience function to set CORS header

### PR DESCRIPTION
**Pull request by crabmusket**
It's easy to set `Access-Control-Allow-Origin` to a single value, but it doesn't currently allow any pattern matching. This convenience function matches the request's `Origin` header against a regex, and if there is a match, sends the request's `Origin` back in the `Access-Control-Allow-Origin` response header.

### CODE REVIEW

**Comment by fumieval** [comment]
The master branch has diverged since the last update. As far as I can tell, the crux of this PR is the following new API:

```haskell
-- | Set the Access-Control-Allow-Origin header to allow access from a single
-- origin.
allowOrigin :: (ScottyError e, Monad m) => T.Text -> ActionT e m ()
allowOrigin origin = setHeader "Access-Control-Allow-Origin" origin

-- | Match the Origin request header against a regular expression. Returns the
-- request origin in the Access-Control-Allow-Origin header if the Origin
-- matches the given pattern.
allowOrigins :: (ScottyError e, Monad m) => T.Text -> ActionT e m ()
allowOrigins "*" = allowOrigin "*"
allowOrigins pattern = do
    maybeOrigin <- header "Origin"
    case maybeOrigin of
        Just origin -> when (isJust $ matchRegex reg $ T.unpack origin) $
            setHeader "Access-Control-Allow-Origin" origin
        Nothing -> return ()
        where reg = mkRegex $ T.unpack pattern
```

They look convenient, but at the same time we want to keep the API small, so it's hard to tell if adding these is better. @RyanGlScott Opinions?

**Comment by RyanGlScott** [comment]
I don't have a particularly strong opinion on this, but what is the difference between setting these headers through `ActionT` and setting them through middleware (e.g., [`wai-cors`](http://hackage.haskell.org/package/wai-cors))? I wonder if the latter is good enough to handle CORS use cases already.

**Comment by fumieval** [comment]
Oh, I didn't know about wai-cors. It seems much better than setting the header invidivually in ActionT.

**Comment by fumieval** [comment]
Closing the PR as there's a much more convenient solution (wai-cors).

**Pull request closed without merging**
