### PR TITLE
Add doctest 

### LINKED ISSUE #353: Add doctest
see https://github.com/quchen/generative-art/blob/master/package.yaml

### PR DESCRIPTION
**Pull request by ocramz**
closes #353

### CODE REVIEW

**Comment by ocramz** [comment]
WIP example docstrings using curl should be ported to use hspec-wai

**Comment by ocramz** [comment]
I've ported a few docstrings to doctest, now we can be sure the examples stay in sync with the code :) 

There's a bit of code duplication but doctest doesn't seem to follow module imports and I'd rather not import 'http-client' into the main scotty library.

**Comment by fumieval** [comment]
Hmm I'm not quite sure what is going on :/

**Comment by ocramz** [comment]
@fumieval  ahh figured this out! it's a GHCi bug, unrelated to doctest. GHCi only recently started supporting multiline imports : https://github.com/scotty-web/scotty/actions/runs/7075697407/job/19258105080?pr=354#step:7:95, related GHC ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/20473

**Comment by ocramz** [comment]
@fumieval  I've turned doctest into a `pure ()` for GHCs older than 9.4.6 , wdyt?  https://github.com/scotty-web/scotty/pull/354/commits/de8d7397068690bf2cb3193023070dea0c4abae0

**Comment by ocramz** [comment]
I'll merge this for now, we can revisit later if needed.

**Pull request merged**
