### PR TITLE
Allow blaze-builder 0.4 (fixes #157)

### LINKED ISSUE #157: blaze-builder 0.4 support
Originally opened at: https://github.com/fpco/stackage/issues/442

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by xich** [comment]
Thanks for the patch!

**Comment by snoyberg** [comment]
Thanks for merging! Do you have an ETA on release to Hackage? I'm trying to get things in order for LTS 2. Even just editing the cabal file on Hackage would be a great help.

**Comment by xich** [comment]
I went ahead and edited the cabal file on Hackage just now.

**Comment by snoyberg** [comment]
Thank you!

**Pull request merged**
