### PR TITLE
read from queryString instead of rawQueryString

### LINKED ISSUE #348: Not able to rewrite the query string using Network.Wai.Middleware.Rewrite
https://hackage.haskell.org/package/wai-extra-3.1.13.0/docs/Network-Wai-Middleware-Rewrite.html

This only updates the `Request.queryString` and doesn't update `Request.rawQueryString`, therefore scotty routes don't pickup on the rewritten `queryString` and continues to read from the old `rawQueryString`.

According to https://hackage.haskell.org/package/wai-3.2.3/docs/Network-Wai.html#v:rawQueryString `rawQueryString` should not be modified.

I'm thinking we should read from queryString instead, to allow for people that need to modify the queryString while keeping rawQueryString read-only.

### PR DESCRIPTION
**Pull request by zachary822**
Fixes #348

### CODE REVIEW

**Review by ocramz — CHANGES_REQUESTED** [review]
Thank you, could you add a test too please?

**Comment by zachary822** [comment]
I'm new to Haskell in general (especially testing), hopefully this is what you are looking for.

**Review by ocramz — CHANGES_REQUESTED** [review]
Thank you @zachary822 , this is very good! Only thing, I wouldn't put the test under "queryParam" but higher up in the `ScottyM` section, in a new section called `middleware`:

```haskell
describe "middleware" $ do
  context "rewrites the query string" $ do
    ...
```

**Review by ocramz — APPROVED** [review]
thanks! 👍

**Pull request merged**
