### PR TITLE
Added support for OPTIONS routes

### PR DESCRIPTION
**Pull request by alvare**
Couldn't add a test since hspec-wai doesn't provide 'options'.

### CODE REVIEW

**Comment by sol** [comment]
@alvare I think you can still test it with `Test.Hspec.Wai.request`.

**Comment by xich** [comment]
@alvare looks good... mind adding the test? `options` was added in hspec/hspec-wai#27

**Comment by alvare** [comment]
Well, it won't build until they merge and deploy it right?

Also, should I update the dependency on hspec-wai?

**Comment by xich** [comment]
This is the definition they added:

```haskell
options :: ByteString -> WaiSession SResponse
options path = request methodOptions path [] ""
```

So maybe just use `request methodOptions path [] ""` for now, and I can fix it later?

**Comment by sol** [comment]
@alvare @xich The latest version of `hspec-wai` on Hackage now has support for `options` (thanks @fujimura, I also added you to the Hackage maintainers list).

**Comment by fujimura** [comment]
@sol Thanks!

**Comment by alvare** [comment]
I've added the tests and ran them successfully.

**Comment by alvare** [comment]
Do you want me to add/change something else?

**Comment by xich** [comment]
Apologies, this slipped out of the bottom of my inbox. Thanks again for the patches!

**Pull request merged**
