### PR TITLE
added Monoid RoutePattern

### PR DESCRIPTION
**Pull request by stacycurl**
When writing routes I've found it useful to be able to do this:

get ("/status" <> accepts "application/json") $ json ...
get "/status $ html ...

Instead of:

get "/status" $
  accept <- header "Accept"
  case (something accept "application/json") ... json ... html ...

I wasn't able to use '<>', I've had to roll my own without using Monoid (I don't want an orphaned instance).

Does this make sense, or is there some other elegant way to achieve this ?

### CODE REVIEW

**Comment by stacycurl** [comment]
You don't deserve pull requests if you just ignore them. Disgusting.

**Comment by creichert** [comment]
Have you seen: https://github.com/scotty-web/scotty/issues/159 ??

**Comment by stacycurl** [comment]
Nope, but that explains it. I think for me scotty is dead; going to go back to plain ol WAI.

**Comment by xich** [comment]
@RyanGlScott mind looking at this?

**Comment by stacycurl** [comment]
Forget it, I'm still frustrated but I understand that priorities have
changed and I expressed my frustration undiplomatically.

I still can't see myself using scotty in the future, though.

**Comment by andygill** [comment]
@stacycurl - This is a completely unacceptable way to talk to @xich & @RyanGlScott. @xich has taken time off to write his PhD, and @RyanGlScott has agreed to try and help clear some backlog.  @xich has already committed countless hours working on scotty, gratis, making a tool that makes all of our lives easier, and I am grateful for the work he has done. So use scotty, fork scotty, or don't use it.  But don't insult my students for not responding quickly enough.

**Comment by stacycurl** [comment]
Acceptance is a activity performed by individuals, I view the phrase "it is
completely unacceptable" as authoritarian. I think you are only qualified
to state what you do or do not accept.

I myself overreached when I said my pr being ignored was disgusting, what I
should have said was that I was disgusted with being ignored.

Additionally I doubt whether the hours are countless, I think "numerous"
would describe them better. I'm am grateful for them too.

I already retracted some of the tone of my original comment, I already
apologised, I will not do so further.

I continue to view an open source project that ignores pull-requests for
over a month as dead, "not quick enough", for me, doesn't fit the bill. A
simple "Sorry, I'm too busy to look at this for awhile" would have done.

I would give your critique more consideration had you attempted to see my
point of view and had you not overreached.

Stacy.

@stacycurl <https://github.com/stacycurl> - This is a completely
unacceptable way to talk to @xich <https://github.com/xich> & @RyanGlScott
<https://github.com/RyanGlScott>. @xich <https://github.com/xich> has taken
time off to write his PhD, and @RyanGlScott <https://github.com/RyanGlScott>
has agreed to try and help clear some backlog. @xich
<https://github.com/xich> has already committed countless hours working on
scotty, gratis, making a tool that makes all of our lives easier, and I am
grateful for the work he has done. So use scotty, fork scotty, or don't use
it. But don't insult my students for not responding quickly enough.

—
Reply to this email directly or view it on GitHub
<https://github.com/scotty-web/scotty/pull/154#issuecomment-97537143>.

**Pull request closed without merging**
