### PR TITLE
bugfix release v 0.20.1

### LINKED ISSUE #323: `ActionT`'s `MonadFail` instance removed in `scotty-0.20`
PR #314 removed the `MonadFail` instance for `ActionT`, which I noticed when trying to upgrade one of my projects:

```
[2 of 2] Compiling Web.Scotty.Comet ( Web/Scotty/Comet.hs, interpreted )

Web/Scotty/Comet.hs:157:28: error:
    • No instance for (MonadFail
                         (Web.Scotty.Internal.Types.ActionT IO))
        arising from a use of ‘fail’
    • In the first argument of ‘($)’, namely ‘fail’
      In the expression:
        fail $ "Expected Object, received: " ++ show wrappedVal
      In a case alternative:
          _ -> fail $ "Expected Object, received: " ++ show wrappedVal
    |
157 |                       _ -> fail $ "Expected Object, received: " ++ show wrappedVal
    |                            ^^^^
```

This isn't documented in the `CHANGELOG` as a breaking change, so I'm unclear if this was intentional or not. If it was intentional, could you document in this in the `CHANGELOG` and suggest a recommended alternative?

### LINKED ISSUE #325: Bugfix release 0.20.1
- [x] Remove `DerivingVia` from `.Types` since we don't even need it
- [x] re-add `MonadFail (ActionT m)` instance
- [x]  re-add `MonadError` `ActionT` instance
- [x] version bump to 0.20.1
- [ ] Deprecate 0.20 on hackage

### PR DESCRIPTION
**Pull request by ocramz**
closes #325  , closes #323

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks!

I do think it's worth raising the upper version bounds on `base` if you don't intend to test pre-8.10 versions of GHC. Otherwise, it's quite easy for build errors to sneak in.

**Comment by ocramz** [comment]
OK I've also re-added the 'MonadError' instance which is also missing in 0.20, but in a specialized form since ActionT does not use checked exceptions.

**Comment by ocramz** [comment]
@RyanGlScott  could you check the instance implementations when you have a minute? I think the overall new design of exceptions is pretty coherent but I'd love your input on this.

**Comment by ocramz** [comment]
Thanks @RyanGlScott !

**Pull request merged**
